### ISSUE TITLE
Chrome Extension Icon Clicking Behavior / Menu

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/EndorsementExtension#28]
Please convert the We Vote icon in the top bar of Chrome to show a menu upon clicking (as opposed to using the click as an on/off toggle)

Please add the following items as menu items:

- Activate Endorsement Tool (vs. Deactivate Endorsement Tool)
- Sign In / Sign Out (if it makes sense technically to add here)
- About We Vote (takes you to https://wevote.us/more/about)
- Manage Extensions (takes you to standard Chrome page for our extension)

**Comment by SailingSteve** [comment]
I once had a dialog here, and I could revive it.

- Activate Endorsement Tool (vs. Deactivate Endorsement Tool)
**This can be done**
- Sign In / Sign Out (if it makes sense technically to add here)
**I don't think this can be done with oAuth redirects from the extension, I tried once and gave up**
- About We Vote (takes you to https://wevote.us/more/about)
**Sure**
- Manage Extensions (takes you to standard Chrome page for our extension)
**Sure, this would be just open a tab at [chrome://extensions/](chrome://extensions/)**

**Comment by SailingSteve** [comment]
I think the real problem is the icon clicking behaviour, and the proposed menu solution was meant to address it.

The solution I went with is as follows:

- Clicking the icon, sends a message to all tabs.
- If the highlighter was active, the extension's panes are removed from all tabs, the highlighter is deactivated, and the count on the icon is disabled.  This will occur irrespectively of which tab was clicked first, and which tab is currently being displayed.
- If the highlighter was inactive, then for every tab (that is not excluded by the never_highlight_on list from voterGuideHighlightsRetrieve), the highlighter will be turned on, and the right and top menus will appear.  If there are no highlights on the page, the counter on the icon will show "0", which will also be a quick visual indicator that the highlighter is on.

**Comment by DaleMcGrew** [comment]
This issue has been replaced with https://github.com/wevote/EndorsementExtension/issues/48
